export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const LOAD_ARTICLES_SUCCESS = "LOAD_ARTICLES_SUCCESS";
export const LOAD_ARTICLES_FAILED = "LOAD_ARTICLES_FAILED";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_FAILED = "LOAD_USERS_FAILED";

export const SAVE_ARTICLE_SUCCESS = "SAVE_ARTICLE_SUCCESS";
export const SAVE_ARTICLE_FAILED = "SAVE_ARTICLE_FAILED";

export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_FAILED = "DELETE_ARTICLE_FAILED";